---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[ca-certificates::default]
    attributes:
